name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-29"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZWU1MWZiMTAtYzgyZC00ZWY2LWE2MGItYWFkMjQ4NzRiZTlkIiwidGVuYW50X2lkIjoiNjYzZjA1YWQ2NzZhMDEzNjFhNmQwMjg3ZTIzNGM2MDgwYTE3ZjRlNDdiODg0M2M0NTcyNmUzNGEzODQ4MjEwNyIsImludGVybmFsX3NlY3JldCI6IjljOTNhYjY3LWRmZGMtNGFhNi1iNDllLTU5OTE2NjJlNmJkYSJ9.V1abrRTkC7ISWqJqs1nss70WvVvLT6yQttKWO71H8GY"
JWT_SECRET = "Harsha"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1